# Header
menu:
  主页: /
  文章: /archives
  萌码: /meng.html
  关于: /about
#rss: 

# Content
excerpt_link: Read More
fancybox: false
#true

# Sidebar
sidebar: left
widgets:
- category
- aboutme
- recent_posts
#- tag
#- tagcloud
#- archive

# Miscellaneous
favicon: /favicon.png
#google_analytics:
#google_plus: 
#twitter: 
#fb_admins:
#fb_app_id: