# Header
menu:
  Home: /
  Archives: /archives
#rss: 

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: left
widgets:
- category
- recent_posts
#- tag
#- tagcloud
#- archive

# Miscellaneous
#google_analytics:
favicon: /favicon.png
#google_plus: 
#twitter: 
#fb_admins:
#fb_app_id: